[package]
name = "GasService"
version = "0.1.0"
edition = "2024"
published-at = "0xc10dd54f42a2f3ebdb8f113bd0a0627934c90e608d1e32e5fd0c7ae4d03d93b3"


[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.38.3" }
VersionControl = { local = "../version_control" }
AxelarGateway = { local = "../axelar_gateway" }

[addresses]
gas_service = "0xc10dd54f42a2f3ebdb8f113bd0a0627934c90e608d1e32e5fd0c7ae4d03d93b3"
